* CHANGES
* LICENSE
* MANIFEST
* README
* Rakefile
* file-temp.gemspec
* certs/djberg96_pub.pem
* lib/file-temp.rb
* lib/file/temp.rb
* lib/file/java/temp.rb
* lib/file/unix/temp.rb
* lib/file/windows/temp.rb
* spec/file_temp_spec.rb
